//===----------------------------------------------------------------------===//
//
// Copyright (C) 2021 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#pragma once

#include <xvec/detail/config.hpp>

#include <concepts>
#include <span>
#include <cstddef>

/// \defgroup simd_permute Permutation functions for basic_vec
/// @brief Functions to permute and reorder data in and between basic_vec values.

namespace _XVEC_NAMESPACE::simd {

namespace detail {

/// Utility to get new vec or mask size
template <simd_size_type _NewSize, simd_size_type _VecOrMaskSize>
inline constexpr simd_size_type new_simd_size = (_NewSize == 0) ? _VecOrMaskSize : _NewSize;

/// Utility to convert a vec into a mask, such that a zero element in the input
/// gives false, otherwise trye in the mask output. This is used to allow
/// constexpr permutations of mask to be implemented by converting a mask into a
/// vec, performing the required permute, and then converting the permuted vec
/// back into a mask.
///
/// The most concise way to convert a vec into a mask is to do `asSimd != 0`
/// but that would invoke operator!= which is unimplemented (issue #538) for
/// very large element types (e.g., `complex<double>`, which is represented as
/// an int128_t). Instead we use a mask generator to built the mask elements
/// one-by-one, which wouldn't be efficient if executed at run-time but it
/// doesn't matter because this is consteval code. :TODO: Even better if this
/// were a consteval function, but until C++23 we can't do that.
///
/// Note that the type of mask is supplied so that the appropriate return type
/// is used by the caller instead of whatever the default would be for the
/// incoming vec (e.g., the incoming vec might be a container, not the actual
/// vec type being permuted.
template<mask_type _M, vec_type _V>
constexpr _M vec_to_mask(const _V& s) { return _M([=](auto i) { return s[i] != 0; }); }

/// Convert a vec value into a vec of container elements. This allows a
/// permute to be written in terms of raw bits in a container without having to
/// care about the actual element type.
template<vec_type _V> constexpr auto to_container(const _V& v)
{
  using _C = detail::container_for_type<typename _V::value_type>;
  return simd_bit_cast<_C>(v);
}

/// Concepts to simplify writing the gather/scatter functions.
///@{
template<typename _Vp, typename _Range, typename _Indexes>
concept gather_from_requires =
  (std::same_as<_Vp, std::nullptr_t>
   || (vec_type<_Vp>
       && simd_same_size<_Vp, _Indexes>
       && detail::explicitly_convertible_to<std::ranges::range_value_t<_Range>, typename _Vp::value_type>));

template<typename _Vp, typename _Range, typename _Indexes>
concept scatter_to_requires =
  (simd_same_size<_Vp, _Indexes> &&
   std::ranges::output_range<_Range, typename _Vp::value_type> &&
   detail::explicitly_convertible_to<typename _Vp::value_type, std::ranges::range_value_t<_Range>>);
///@}

} // namespace detail

/// @brief Permute the elements in a vec value using a generator function to compute the indexing.
/// @{
/// @ingroup simd_permute
/// @tparam _NewSize The number of elements required in the permuted output basic_vec.
/// @tparam _Vp The type of the basic_vec value to permute
/// @param v The value to permute
/// @param fn The index generator function. Given an index position in the
/// output basic_vec this function should return the index of the element to use from
/// the input value. The function may accept an optional parameter giving the
/// size of v.
/// @return A new basic_vec value where every element takes as its input the element generated by the index functon.
template<simd_size_type _NewSize = 0, vec_type _Vp>
constexpr auto
permute(const _Vp& v, detail::index_generator_function auto&& fn) {
  constexpr auto new_simd_size = detail::new_simd_size<_NewSize, _Vp::size()>;
  return detail::generated_permute<new_simd_size>(target, v, std::forward<decltype(fn)>(fn)); }

template<simd_size_type _NewSize = 0, mask_type _Mask>
constexpr auto
permute(const _Mask& mask, detail::index_generator_function auto&& fn) {
  constexpr auto new_simd_size = detail::new_simd_size<_NewSize, _Mask::size()>;

  if (std::is_constant_evaluated())
  {
    auto asS = permute<new_simd_size>(+mask, std::forward<decltype(fn)>(fn));
    using asM = resize_t<new_simd_size, _Mask>;
    return detail::vec_to_mask<asM>(asS);
  }
  else
    return detail::generated_permute<new_simd_size>(target, mask, std::forward<decltype(fn)>(fn));
}
///@}

/// @brief Permute a vec or mask value by the unsigned integral indexes supplied in another basic_vec value.
/// @tparam _V The type of the basic_vec or basic_mask value to permute
/// @tparam _I The type of the index basic_vec value containing unsigned integral values
/// @param v The basic_vec or basic_mask value to permute
/// @param indexes The indexes by which to permute
/// @return The contents of v permuted by the indexes. The output of each element position is v[idx[iota()]].
template<vec_or_mask_type _V, vec_integral _I>
constexpr resize_t<_I::size, _V> permute(const _V& v, const _I& indexes)
{
  if (std::is_constant_evaluated())
    return resize_t<_I::size, _V>([=](auto i) { return v[indexes[i]]; });
  else
    return detail::permute(target, v, indexes);
}

/// @brief Compress a basic_vec or basic_mask value by a mask. The elements
/// corresponding to any set mask bits will be packed contiguously into the
/// output. Excess elements will be zeroed. The output basic_vec will have elements
/// of the same type as the input basic_vec, and the same number of elements as the
/// input mask.
/// @{
/// @tparam _V The vec type
/// @param v The values to permute
/// @param selector The mask by which to permute.
/// @return The active elements of the basic_vec or basic_mask selected by the mask and packed contiguously into the output.
template<vec_type _V>
constexpr _V
compress(const _V& v, const typename _V::mask_type& selector)
{
  using _Tp = typename _V::value_type;

  if (std::is_constant_evaluated())
    return compress(v, selector, _Tp()); // The fill-with-value overload handles consteval.
  else
  {
    const auto out = detail::compress_by_mask(target, detail::to_container(v), selector);
    return simd_bit_cast<_Tp>(out);
  }
}

template<vec_type _V>
constexpr _V
compress(const _V& v, const typename _V::mask_type& selector, const typename _V::value_type& fill_value)
{
  using _Tp = typename _V::value_type;
  if (std::is_constant_evaluated()) {
    std::array<_Tp, _V::size()> r; // Can't write to a vec[] so use an array instead.
    r.fill(fill_value);
    int nextOutPos = 0;
    for (int i=0; i<_V::size(); ++i)
      if (selector[i])
        r[nextOutPos++] = v[i];
    return _V(r);
  }
  else
  {
    using _C = detail::container_for_type<_Tp>;
    const auto fillAsC = std::bit_cast<_C>(fill_value);
    auto t = detail::compress_by_mask(target, detail::to_container(v), selector, fillAsC);
    return simd_bit_cast<_Tp>(t);
  }
}

/// Compress one mask using another mask.
template<mask_type _M>
constexpr _M compress(const _M& v, const std::type_identity_t<_M>& selector)
{
  if (std::is_constant_evaluated())
    return detail::vec_to_mask<_M>(compress(+v, selector, false));
  else
    return detail::compress_mask_by_mask(target, v, selector);
}

/// Compress one mask using another mask.
template<mask_type _M>
constexpr _M compress(const _M& v, const std::type_identity_t<_M>& selector, bool fill_value)
{
  if (std::is_constant_evaluated())
    return detail::vec_to_mask<_M>(compress(+v, selector, fill_value));
  else
    return detail::compress_mask_by_mask(target, v, selector, fill_value);
}
///@}

/// @brief Expand a vec or mask value by a mask. The value returned in an
/// object in which the first [0..reduce_count(selector)) values are copied to
/// those output elements whose respective selector elements are set. Any output
/// elements whose respective selector elements are not set will have the
/// corresponding element from original copied into that position.
/// @{
/// @tparam _V The vec type
/// @param v The values to permute
/// @param selector The mask by which to permute.
/// @param original The value whose elements should be copied to the output in the positions where the corresponding mask bit is clear.
/// @return The active elements of the vec or mask selected by the mask and packed contiguously into the output.
template<vec_type _V>
constexpr _V
expand(const _V& v, const typename _V::mask_type& selector, const _V& original = {})
{
  using _Tp = typename _V::value_type;

  if (std::is_constant_evaluated())
  {
    std::array<_Tp, _V::size()> r;
    int nextInPos = 0;
    for (int i=0; i<_V::size(); ++i)
      r[i] = selector[i] ? v[nextInPos++] : original[i];
    return _V(r);
  }
  else
  {
    const auto out = detail::expand_by_mask(target, detail::to_container(v), selector, detail::to_container(original));
    return simd_bit_cast<_Tp>(out);
  }
}

template<mask_type _M>
constexpr _M expand(const _M& v, const std::type_identity_t<_M>& selector, const _M& original = {})
{
  if (std::is_constant_evaluated())
    return detail::vec_to_mask<_M>(expand(+v, selector, +original));
  else
    return detail::expand_mask_by_mask(target, v, selector, original);
}
///@}

/// @brief Gather the contents of a contiguous range using the integral indexes supplied in another vec value.
/// @tparam _Vp A deduced type which the caller can override to specify the return type. This allows type conversions.
/// @tparam _Range The range type from which to read.
/// @tparam _Indexes The type of the vec indexes used in the gather.
/// @tparam _Flags Flag type controlling the memory access.
/// @param r A contiguous range of known size which references a block of data
/// from which to gather. Only elements inside the range will be accessed. Any
/// indexes outside the range will return undefined values.
/// @param indexes The indexes from which to gather.
/// @return A new vec value formed by reading the range from each index element range[idx[iota()]].
///@{
template<typename _Vp = std::nullptr_t, detail::contiguous_sized_range _Range, vec_integral _Indexes, typename... _Flags>
requires detail::gather_from_requires<_Vp, _Range, _Indexes>
constexpr auto
partial_gather_from(_Range&& r, const _Indexes& indexes, flags<_Flags...> f = {})
{
  using _RangeSimd = rebind_t<std::ranges::range_value_t<_Range>, _Indexes>;
  using _OutSimd = std::conditional_t<std::same_as<_Vp, std::nullptr_t>, _RangeSimd, _Vp>;

  detail::mandates_for_load(r, _OutSimd{}, f);

  if (std::is_constant_evaluated())
    return _OutSimd([=](auto i) -> typename _OutSimd::value_type { return r[indexes[i]]; });
  else
    return _OutSimd(detail::gather_from(target, r, indexes, f));
}

/// Unchecked variant of gather.
template<typename _Vp = std::nullptr_t, detail::contiguous_sized_range _Range, vec_integral _Indexes, typename... _Flags>
requires detail::gather_from_requires<_Vp, _Range, _Indexes>
constexpr auto
unchecked_gather_from(_Range&& r, const _Indexes& indexes, flags<_Flags...> f = {})
  { return partial_gather_from<_Vp>(r, indexes, detail::add_unchecked_flag(f)); }

template<typename _Vp = std::nullptr_t, detail::contiguous_sized_range _Range, vec_integral _Indexes, typename... _Flags>
requires detail::gather_from_requires<_Vp, _Range, _Indexes>
constexpr auto
partial_gather_from(_Range&& r, const typename _Indexes::mask_type& mask,
                    const _Indexes& indexes, flags<_Flags...> f = {})
{
  using _RangeSimd = rebind_t<std::ranges::range_value_t<_Range>, _Indexes>;
  using _OutSimd = std::conditional_t<std::same_as<_Vp, std::nullptr_t>, _RangeSimd, _Vp>;

  detail::mandates_for_load(r, _OutSimd{}, f);

  if (std::is_constant_evaluated())
    return _OutSimd([=](auto i) -> typename _OutSimd::value_type { return mask[i] ? r[indexes[i]] : typename _OutSimd::value_type(); });
  else
    return _OutSimd(detail::gather_from(target, r, mask, indexes, f));
}

// Unchecked variant of masked gather_from
template<typename _Vp = std::nullptr_t, detail::contiguous_sized_range _Range, vec_integral _Indexes, typename... _Flags>
requires detail::gather_from_requires<_Vp, _Range, _Indexes>
constexpr auto
unchecked_gather_from(_Range&& r, const typename _Indexes::mask_type& mask,
                      const _Indexes& indexes, flags<_Flags...> f = {})
  { return partial_gather_from<_Vp>(r, mask, indexes, detail::add_unchecked_flag(f)); }

///@}

/// @brief Scatter the contents of a basic_vec into memory at the integral index positions supplied in another basic_vec value.
/// @tparam _Vp The type of the values to scatter to memory.
/// @tparam _Indexes The type of the indexes used in the scatter.
/// @tparam _Range The type of the range to which to write.
/// @param values The values to scatter to memory.
/// @param r A contiguous range which references a block of data to which to scatter.
/// @param indexes The indexes to which to scatter.
/// @{
template <detail::contiguous_sized_range _Range, vec_type _Vp, vec_integral _Indexes, typename... _Flags>
requires detail::scatter_to_requires<_Vp, _Range, _Indexes>
constexpr void
partial_scatter_to(const _Vp& values, _Range&& r, const _Indexes& indexes, flags<_Flags...> f = {})
{
  detail::mandates_for_store(values, r, f);

  if (std::is_constant_evaluated())
    for (int i=0; i<_Vp::size; ++i) r[indexes[i]] = values[i];
  else
    detail::scatter_to(target, values, r, indexes, f);
}

template <detail::contiguous_sized_range  _Range, vec_type _Vp, vec_integral _Indexes, typename... _Flags>
requires detail::scatter_to_requires<_Vp, _Range, _Indexes>
constexpr void
partial_scatter_to(const _Vp& values, _Range&& r, const typename _Indexes::mask_type& mask, const _Indexes& indexes, flags<_Flags...> f = {})
{
  detail::mandates_for_store(values, r, f);

  if (std::is_constant_evaluated())
  {
    for (int i=0; i<_Vp::size; ++i)
      if (mask[i])
        r[indexes[i]] = values[i];
  }
  else
    detail::scatter_to(target, values, r, mask, indexes, f);
}

template <detail::contiguous_sized_range _Range, vec_type _Vp, vec_integral _Indexes, typename... _Flags>
requires detail::scatter_to_requires<_Vp, _Range, _Indexes>
constexpr void
unchecked_scatter_to(const _Vp& values, _Range&& r, const _Indexes& indexes, flags<_Flags...> f = {})
  { partial_scatter_to(values, r, indexes, detail::add_unchecked_flag(f)); }

template <detail::contiguous_sized_range  _Range, vec_type _Vp, vec_integral _Indexes, typename... _Flags>
requires detail::scatter_to_requires<_Vp, _Range, _Indexes>
constexpr void
unchecked_scatter_to(const _Vp& values, _Range&& r, const typename _Indexes::mask_type& mask, const _Indexes& indexes, flags<_Flags...> f = {})
  { partial_scatter_to(values, r, mask, indexes, detail::add_unchecked_flag(f)); }

///@}

} // namespace _XVEC_NAMESPACE::simd
